Models/Quote.cs
using System.ComponentModel.DataAnnotations;

namespace gestion_devis.Models
{
    public class Quote
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public Client Client { get; set; }

        [Required]
        public DateTime CreationDate { get; set; }

       
        [Range(0, 100)]
        public double Discount { get; set; }

       
        [Range(0, double.MaxValue)]
        public double TotalPrice { get; set; }

        public List<QuoteProduct> QuoteProducts { get; set; }

        public byte[] PdfData { get; set; }

        public Quote()
        {
            QuoteProducts = new List<QuoteProduct>();
        }
    }
}

Controllers/QuoteController.cs
using gestion_devis.Models;
using gestion_devis.Repositories;
using gestion_devis.ViewModels;
using gestion_devis.Utils;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace gestion_devis.Controllers
{
    public class QuoteController : Controller
    {
        private readonly IQuoteRepository _quoteRepository;
        private readonly PdfService _pdfService;

        public QuoteController(IQuoteRepository quoteRepository, PdfService pdfService)
        {
            _quoteRepository = quoteRepository;
            _pdfService = pdfService;
        }

        // Affiche la page d'accueil des devis
        public IActionResult Index()
        {
            var quotes = _quoteRepository.GetAllQuotes();
            return View(quotes);
        }

        // Affiche le formulaire de création d'un devis
        public IActionResult Create()
        {
            var viewModel = CreateQuoteViewModel();
            return View(viewModel);
        }

        // Traite la soumission du formulaire de création d'un devis
        [HttpPost]
        public IActionResult Create(CreateQuoteViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                int selectedClientId = viewModel.SelectedClientId;
                var client = GetClient(selectedClientId);

                if (client != null)
                {
                    var quote = CreateQuoteFromViewModel(viewModel, client);
                    _quoteRepository.AddQuote(quote);
                    _quoteRepository.SaveChanges();

                    var selectedProducts = GetSelectedProductsFromJson(Request.Form["SelectedProducts"]);
                    AddQuoteProducts(quote, selectedProducts);

                    _pdfService.GeneratePdfFromQuote(quote);

                    return RedirectToAction("Index");
                }
            }

            var clients = _quoteRepository.GetAllClients().ToList();
            var products = _quoteRepository.GetAllProducts().ToList();

            viewModel.Clients = clients;
            viewModel.Products = products;

            return View(viewModel);
        }

        // Crée et retourne le ViewModel pour le formulaire de création de devis
        private CreateQuoteViewModel CreateQuoteViewModel()
        {
            var clients = _quoteRepository.GetAllClients().ToList();
            var products = _quoteRepository.GetAllProducts().ToList();

            var viewModel = new CreateQuoteViewModel
            {
                Clients = clients,
                Products = products
            };

            return viewModel;
        }

        // Récupère le client à partir de son ID
        private Client GetClient(int clientId)
        {
            return _quoteRepository.GetClientById(clientId);
        }

        // Crée un objet Quote à partir du ViewModel et du client sélectionné
        private static Quote CreateQuoteFromViewModel(CreateQuoteViewModel viewModel, Client client)
        {
            var quote = new Quote
            {
                Client = client,
                CreationDate = DateTime.Now,
                TotalPrice = viewModel.TotalPrice,
                Discount = viewModel.Discount,
            };

            return quote;
        }

        // Récupère les produits sélectionnés à partir de la chaîne JSON
        private static List<SelectedProductViewModel> GetSelectedProductsFromJson(string selectedProductsJson)
        {
            return JsonSerializer.Deserialize<List<SelectedProductViewModel>>(selectedProductsJson);
        }

        // Ajoute les produits du devis à la base de données
        private void AddQuoteProducts(Quote quote, List<SelectedProductViewModel> selectedProducts)
        {
            foreach (var selectedProduct in selectedProducts)
            {
                var product = _quoteRepository.GetProductById(selectedProduct.ProductId);
                if (product != null)
                {
                    var quoteProduct = new QuoteProduct
                    {
                        QuoteId = quote.Id,
                        ProductId = product.Id,
                        Quantity = selectedProduct.Quantity
                    };

                    _quoteRepository.AddQuoteProduct(quoteProduct);
                }
            }
        }

        [HttpPost]
        public IActionResult DeleteQuote(int id)
        {
            _quoteRepository.DeleteQuote(id);
            _quoteRepository.SaveChanges();

            var quotes = _quoteRepository.GetAllQuotes();
            return PartialView("_QuoteTable", quotes);
        }

        public IActionResult SortQuote(string sortBy)
        {
            IQueryable<Quote> quotesQuery = _quoteRepository.GetAllQuotes().AsQueryable();

            quotesQuery = sortBy switch
            {
                "client" => quotesQuery.OrderBy(q => q.Client.Name),
                "date" => quotesQuery.OrderBy(q => q.CreationDate),
                _ => quotesQuery.OrderBy(q => q.Client.Name),
            };

            var quotes = quotesQuery.ToList();

            return PartialView("_QuoteTable", quotes);
        }

        public IActionResult DownloadPdf(int id)
        {
            var quote = _quoteRepository.GetQuoteById(id);

            if (quote == null || quote.PdfData == null)
            {
                return NotFound(); // Gérer le cas où le devis ou le PDF n'est pas trouvé
            }

            return View(quote);
        }

        public IActionResult GetPdfContent(int id)
        {
            var quote = _quoteRepository.GetQuoteById(id);
            if (quote == null || quote.PdfData == null)
            {
                return NotFound(); // Gérer le cas où le devis ou le PDF n'est pas trouvé
            }

            return File(quote.PdfData, "application/pdf");
        }
    }
}

Views/Quote/Create.cshtml
@{
    ViewData["Title"] = "Devis";
}
@model gestion_devis.ViewModels.CreateQuoteViewModel

@section Scripts {
    <script src="/js/Quote/create.js"></script>
}

<h2>Créer un devis</h2>

@using (Html.BeginForm("Create", "Quote", FormMethod.Post))
{
    <!-- Sélection du client -->
    <div class="form-group">
        @Html.LabelFor(m => m.SelectedClientId, "Client :")
        <select id="clientList" name="SelectedClientId" class="form-control">
            <option value="">Sélectionnez un client</option>
            @foreach (var client in Model.Clients)
            {
                <!-- Options du client avec des attributs de données pour stocker les informations du client -->
                <option value="@client.Id"
                        data-client-name="@client.Name"
                        data-client-email="@client.Email"
                        data-client-phone-number="@client.PhoneNumber"
                        data-client-street="@client.Address.Street"
                        data-client-city="@client.Address.City"
                        data-client-postal-code="@client.Address.PostalCode">@client.Name</option>
            }
        </select>
    </div>

    <!-- Détails du client sélectionné -->
    <div id="clientDetails" style="display: none;">
        <h4>Informations du client :</h4>
        <div id="clientName"></div>
        <div id="clientEmail"></div>
        <div id="clientPhoneNumber"></div>
        <div id="clientAddress"></div>

        <!-- Champ caché pour stocker l'ID du client sélectionné -->
        <input type="hidden" id="selectedClientId" name="SelectedClientId" value="" />
    </div>

    <!-- Sélection du produit -->
    <div class="form-group">
        <select id="productList" name="SelectedProductId" class="form-control">
            <option value="">Sélectionnez un produit</option>
            @foreach (var product in Model.Products)
            {
                <!-- Options du produit avec des attributs de données pour stocker les informations du produit -->
                <option value="@product.Id" data-product-description="@product.Description" data-product-price="@product.Price">@product.Name</option>
            }
        </select>
    </div>

    <!-- Tableau des produits sélectionnés -->
    <table id="selectedProductsTable" class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Description</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Prix total</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <!-- Champ de remise en pourcentage -->
    <div class="form-group">
        <label for="discount">Remise en pourcentage :</label>
        <input type="text" step="0.01" id="discount" name="discount" class="form-control" value="0" onchange="calculateTotalPrice()" />
    </div>

    <!-- Champ du prix total du devis -->
    <div class="form-group">
        <label for="totalPrice">Prix total du devis :</label>
        <input type="text" step="0.01" id="totalPrice" name="totalPrice" value="0" lang="fr" class="form-control" readonly/>
    </div>

    <!-- Champ caché pour stocker les produits sélectionnés sous forme de chaîne JSON -->
    <input type="hidden" id="selectedProducts" name="SelectedProducts" value="" />

    <!-- Bouton de création du devis -->
    <button type="submit" onclick="prepareSelectedProducts()" class="btn btn-primary">Créer le devis</button>
}

Views/Quote/DownloadPdf.cshtml
@model gestion_devis.Models.Quote


<iframe src="@Url.Action("GetPdfContent", new { id = Model.Id })" width="100%" height="800px"></iframe>

Views/Quote/Index.cshtml
@{
    ViewData["Title"] = "Devis";
}
@model List<gestion_devis.Models.Quote>

<h1>Liste des devis</h1>

<!-- List déroulante pour trier les devis par Date/Client -->
<div class="form-group">
    <label for="sortSelect">Trier par :</label>
    <select id="sortSelect" class="form-control">
        <option value="date">Date</option> <!-- Option de tri par date -->
        <option value="client">Client</option> <!-- Option de tri par client -->
    </select>
</div>

<!-- Tableau pour afficher la liste des devis -->
<table id="quoteTable" class="table">
    <!-- En-tête du tableau -->
    <thead>
        <tr>
            <th>Nom du client</th>
            <th>Date</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <!-- Boucle sur chaque devis en base de données -->
        @foreach (var quote in Model)
        {
            <tr>
                <td>@quote.Client.Name</td>
                <td>@quote.CreationDate</td>
                <td>
                    <a href="@Url.Action("DownloadPdf", new { id = quote.Id })" target="_blank">Devis au format PDF</a> <!-- Lien pour accéder au devis au format PDF -->
                </td>
                <td>
                    <button class="btn btn-danger" onclick="deleteQuote(@quote.Id)">Supprimer</button> <!-- Bouton pour supprimer le devis -->
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Url.Action("Create", "Quote")">Créer un devis</a> <!-- Bouton pour créer un devis -->
</div>

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var sortSelect = document.getElementById("sortSelect");
            var quoteTable = document.getElementById("quoteTable");

            sortSelect.addEventListener("change", function () {
                var sortBy = sortSelect.value;

                // Effectuer une requête AJAX pour récupérer les devis triés
                var request = new XMLHttpRequest();
                request.open("GET", "@Url.Action("SortQuote")?sortBy=" + sortBy);

                request.onload = function () {
                    if (request.status === 200) {
                        quoteTable.innerHTML = request.responseText;
                    }
                };

                request.send();
            });
        });
    </script>
    <script>
        function deleteQuote(quoteId) {
            if (confirm("Êtes-vous sûr de vouloir supprimer ce devis ?")) {
                // Effectuer une requête AJAX pour supprimer le devis
                var request = new XMLHttpRequest();
                request.open("POST", "@Url.Action("DeleteQuote")?id=" + quoteId);

                request.onload = function () {
                    if (request.status === 200) {
                        // Actualiser la table des devis
                        var quoteTable = document.getElementById("quoteTable");
                        quoteTable.innerHTML = request.responseText;
                    }
                };

                request.send();
            }
        }
    </script>
}

Views/Quote/_QuoteTable.cshtml
@model List<gestion_devis.Models.Quote>

<thead>
    <tr>
        <th>Nom du client</th>
        <th>Date</th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
    @foreach (var quote in Model)
    {
        <tr>
            <td>@quote.Client.Name</td>
            <td>@quote.CreationDate</td>
            <td>
                <a href="@Url.Action("DownloadPdf", new { id = quote.Id })" target="_blank">Devis au format PDF</a>
            </td>
            <td>
                <button class="btn btn-danger" onclick="deleteQuote(@quote.Id)">Supprimer</button>
            </td>
        </tr>
    }
</tbody>